### ISSUE TITLE
How to use the client?

### ISSUE THREAD

**Issue by davej** [SirAlex/RemoteSignTool#6]
Thanks for this! This is a dupe of #3 but I didn't see an answer.

I have the server setup and working, how do I use the client? Also, would it be possible for you to briefly detail the protocol? I am hoping to create a Linux client so that I can send the binary from our Linux CI server.

**Comment by SirAlex** [comment]
Hi, Client emulates original signtool.exe (It send file to server and command line parameters, server executes original signtool and send back signed file)

**Comment by davej** [comment]
Thanks @SirAlex. My client needed to be on linux. Here's a simple client that I wrote using the `request` library in node. Hope it's useful to somebody.

```js
function encodeRFC5987ValueChars(str) {
  return (
    encodeURIComponent(str)
      .replace(/['()]/g, escape)
      .replace(/\*/g, "%2A")
      .replace(/%(?:7C|60|5E)/g, unescape)
  );
}

const filePath = '/path/to/your/app.exe';
const fileName = 'app.exe';

request(
  {
    url: `http://some-server:8090/sign?file=${encodeURIComponent(
      fileName
    )}`,
    headers: {
      "cache-control": "no-cache",
      "content-disposition": `attachment; filename=${encodeRFC5987ValueChars(
        fileName
      )}`,
      "content-type": "application/octet-stream"
    },
    encoding: null,
    method: "POST",
    body: fs.createReadStream(filePath)
  },
  (error, response, body) => {
    fs.writeFileSync(filePath, body); // Overwrite app with signed app
  }
);
```

**Comment by kovzol** [comment]
@davej I'd try to use your code but it does not work for me under node 8.10.0. I inserted two lines in the beginning:
```
var request = require('request');
var fs = require('fs');
```
but I still get an error:
```
buffer.js:202
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at new Buffer (buffer.js:158:17)
    at Request.init (/usr/lib/nodejs/request/index.js:342:21)
    at new Request (/usr/lib/nodejs/request/index.js:124:8)
    at request (/usr/lib/nodejs/request/index.js:1279:11)
    at Object.<anonymous> (/path/to/my/client.js:16:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```
Do you have any hint what to do from this point? Thanks!
